name: 构建特殊平台的 sm64coopdx（不含 DiscordLib）

on:
  workflow_dispatch: # 允许网页端手动点击触发
    inputs:
      arm64:
        description: "构建 ARM64 Linux"
        type: boolean
        default: true
      freebsd:
        description: "构建 FreeBSD"
        type: boolean
        default: true

jobs:
  build-arm64-linux:
    runs-on: ubuntu-24.04-arm
    if: ${{ inputs.arm64 == true }}
    name: arm64 Linux（树莓派/Termux）
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ====================================================================
      # 【如果你用的是公开仓库 + Secret 方案，请删掉下面三行最前面的 # 号以解除注释】
      # - name: Decode Baserom from Secrets
      #   run: |
      #     echo "${{ secrets.BASE64_ROM }}" | base64 -d > baserom.us.z64
      # ====================================================================

      - name: Install Native Dependencies
        run: |
          sudo apt-get update
          # 因为本身就是 arm64 系统，直接装就是原生 arm64 开发库，省心到极点
          sudo apt-get install -y build-essential git python3 libsdl2-dev libglew-dev libcurl4-openssl-dev zlib1g-dev bsdmainutils libx11-dev

      - name: Compile Game Natively
        run: |
          # 没有任何交叉编译参数，核心全开 (-j$(nproc))，起飞！
          make DISCORDRPC=0 -j$(nproc)

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sm64coopdx_arm64_linux
          path: build/us_pc/

  build-freebsd:
    runs-on: ubuntu-22.04
    if: ${{ inputs.freebsd == true }}
    name: FreeBSD 构建（BSD 大佬我哭了）

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: freebsd vm/build
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          sync: rsync # 同步文件
          prepare: |
            pkg update
            pkg install -y gmake sdl2 glew python3 git pkgconf
            ln -sf /usr/local/bin/python3 /usr/local/bin/python
          run: |
            echo "开始编译。请坐和放宽"
            # 使用 c++。应该是什么g++找不到。我试试这个
            gmake CC=cc CXX=c++ BETTERCAMERA=1 EXTERNAL_DATA=1 -j$(sysctl -n hw.ncpu)

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sm64coopdx-freebsd-binaries
          path: build/us_pc/
